#!/bin/sh
# Build Hivemind and put it where the terminal and Spotlight can find it:
#
#   ~/Applications/Hivemind.app   symlink, so a rebuild is picked up
#   ~/.local/bin/hivemind         launcher, also runs the CLI checks
#
# Re-run it after moving the repo; the launcher records an absolute path.
set -e
cd "$(dirname "$0")/.."
REPO="$PWD"

./build.sh

mkdir -p "$HOME/Applications" "$HOME/.local/bin"
ln -sfn "$REPO/Hivemind.app" "$HOME/Applications/Hivemind.app"

cat > "$HOME/.local/bin/hivemind" <<EOF
#!/bin/sh
# Generated by $REPO/scripts/install.sh
APP="$REPO/Hivemind.app"
[ -d "\$APP" ] || { echo "hivemind: not built. run $REPO/build.sh" >&2; exit 1; }
# No arguments opens the app; anything else runs the binary, so
# "hivemind --dump" prints the sessions and the self-checks.
[ \$# -eq 0 ] && exec open "\$APP"
exec "\$APP/Contents/MacOS/Hivemind" "\$@"
EOF
chmod +x "$HOME/.local/bin/hivemind"

printf 'installed:\n  %s\n  %s\n' \
    "$HOME/Applications/Hivemind.app" "$HOME/.local/bin/hivemind"

case ":$PATH:" in
    *":$HOME/.local/bin:"*) ;;
    *) echo "note: ~/.local/bin is not on your PATH" ;;
esac
